### ISSUE TITLE
队伍伤害面板的UI建议（个人看法仅供参考）

### ISSUE THREAD

**Issue by Oishiimono** [AFanSKyQs/FanSky_Qs#12]
目前感觉有这样几个问题，但是UI这种吧是比较主观的，自己不一定代表大多数人，仅供大佬参考:
（1）分区域的字体颜色较多，比如左上是红色、右上是白色、中间充能是紫色、下面是白色和粉色
（2）结合（1），字体颜色多但背景颜色浅，容易导致文字识别困难，建议可以尽量用相对统一的文字颜色，同时把背景整体选暗色的或者用黑色滤镜过滤
（3）充能部分信息量不多，其实可以不用占这么大空间；饼图本来占的空间就比较大，可以考虑用条形、电池形状等
（4）饼图的对比颜色主要是四个，跟饼图数据字体同色，所以也要考虑这部分的字体、图形和背景的对比度，不然看起来也有点不容易
个人感觉喵佬Miao-plugin那个深蓝色低、铜金色字体的搭配也可以作为一种参考；当然更多还是看大佬个人偏好啦~

感谢大佬的开发，这个功能是比较实用的

**Comment by Oishiimono** [comment]
> 目前感觉有这样几个问题，但是UI这种吧是比较主观的，自己不一定代表大多数人，仅供大佬参考: （1）分区域的字体颜色较多，比如左上是红色、右上是白色、中间充能是紫色、下面是白色和粉色 （2）结合（1），字体颜色多但背景颜色浅，容易导致文字识别困难，建议可以尽量用相对统一的文字颜色，同时把背景整体选暗色的或者用黑色滤镜过滤 （3）充能部分信息量不多，其实可以不用占这么大空间；饼图本来占的空间就比较大，可以考虑用条形、电池形状等 （4）饼图的对比颜色主要是四个，跟饼图数据字体同色，所以也要考虑这部分的字体、图形和背景的对比度，不然看起来也有点不容易 个人感觉喵佬Miao-plugin那个深蓝色低、铜金色字体的搭配也可以作为一种参考；当然更多还是看大佬个人偏好啦~
> 
> 感谢大佬的开发，这个功能是比较实用的

![image](https://user-images.githubusercontent.com/34758515/227728960-9ab9d41a-59bd-444d-be62-bf72cffae916.png)

**Comment by AFanSKyQs** [comment]
目前样式确实还有很大问题，信息显示不够直观（主要想引入一些acg背景，但是撮合得不大适配污染了整体信息体，如果是原背景其实信息已经比较清晰了），我还是不太适合UI设计(ww..)，还有渲染精度也不够，图片默认是比较糊的，样式都还在调，会优化的喵~
