### ISSUE TITLE
账号问题

### ISSUE THREAD

**Issue by yydzjdwji** [AFanSKyQs/FanSky_Qs#13]
难蚌，bot十几个主人首次启动群发消息直接给兄弟干封号了，能不能优化一下只给第一个主人发

**Comment by AFanSKyQs** [comment]
十分抱歉，没考虑到有这么多主人的情况，这次github的更新推送可能也并发了QAQ.....

**Comment by AFanSKyQs** [comment]
麻烦更新重启一下，已经全部调节了(┳Д┳)
