### ISSUE TITLE
抢指令了

### ISSUE THREAD

**Issue by 2861164410** [AFanSKyQs/FanSky_Qs#16]
成就成就的插件录入指令被抢了
![Screenshot_20230331_045954](https://user-images.githubusercontent.com/118712290/228963336-05d26e8f-75d1-4830-86be-90b90cf1ea70.jpg)
成就查漏能用只有成就录入被抢了

**Comment by AFanSKyQs** [comment]
确定最新了吗，这个早就修了的
![Screenshot_20230331_113543](https://user-images.githubusercontent.com/59954030/229016574-1746973a-9638-41df-be36-afa141f5a63a.jpg)

**Comment by 2861164410** [comment]
> 确定最新了吗，这个早就修了的 ![Screenshot_20230331_113543](https://user-images.githubusercontent.com/59954030/229016574-1746973a-9638-41df-be36-afa141f5a63a.jpg)

![Screenshot_20230331_120946](https://user-images.githubusercontent.com/118712290/229020642-ae86e0d4-5b6e-4b85-9a58-39ce5e8fc0f9.jpg)
是最新的啊

**Comment by 2861164410** [comment]
> 确定最新了吗，这个早就修了的 ![Screenshot_20230331_113543](https://user-images.githubusercontent.com/59954030/229016574-1746973a-9638-41df-be36-afa141f5a63a.jpg)

![Screenshot_20230331_120946](https://user-images.githubusercontent.com/118712290/229020708-bce76668-1061-4d8e-b291-0e7ac129c932.jpg)

**Comment by 2861164410** [comment]
> 确定最新了吗，这个早就修了的 ![Screenshot_20230331_113543](https://user-images.githubusercontent.com/59954030/229016574-1746973a-9638-41df-be36-afa141f5a63a.jpg)

![Uploading -77fd2ea30f4b4b72.png…]()
这个还是这样

**Comment by 2861164410** [comment]
> 确定最新了吗，这个早就修了的 ![Screenshot_20230331_113543](https://user-images.githubusercontent.com/59954030/229016574-1746973a-9638-41df-be36-afa141f5a63a.jpg)

![-77fd2ea30f4b4b72](https://user-images.githubusercontent.com/118712290/229021297-fa536d0a-9559-43a4-85df-2711e3ee514b.png)
还是这样

**Comment by AFanSKyQs** [comment]
刚刚给最外面的一层代码删除了，应该可以了~

**Comment by AFanSKyQs** [comment]
丢，Gitee这几天没有自动同步，导致Gitee那边落后版本，刚刚手动同步过去了
