### ISSUE TITLE
FanSky_Qs仓库更新检测

### ISSUE THREAD

**Issue by DigitLion** [AFanSKyQs/FanSky_Qs#22]
不知道什么时候突然加了一个自动仓库检测的计划任务
希望作者能取消掉
eg:
在安装自动化插件后 执行#任务表：
任务代号: 8
任务名: FanSky_Qs仓库更新检测
任务执行式: 0 0/2 * * * ? 
下一次调用时间: 2023-4-4 19:02:00

**Comment by lintonxue00** [comment]
我也发现，不是很喜欢这个功能

**Comment by AFanSKyQs** [comment]
增加了开关喵~：https://github.com/AFanSKyQs/FanSky_Qs/commit/80baa647467bd6d00b0f6bde1cb5a04dc09e5d65
