### ISSUE TITLE
一眼丁真功能报错

### ISSUE THREAD

**Issue by WillyerQ** [AFanSKyQs/FanSky_Qs#26]
发指令一眼丁真报错
![Screenshot_2023-04-15-16-53-01-618_com microsoft rdc androidx](https://user-images.githubusercontent.com/126785476/232202632-089f07c4-11fa-4964-9499-ce94485a81a0.jpg)

如图

**Comment by AFanSKyQs** [comment]
因为你触发的不是我插件的噢，你应该是装了其他这个指令的js或plugins，通过api请求获取的，但是请求有问题所以报错了；如果要使用本插件的，采用的是本地存储，不会有这种问题，删除其他的同类型即可
