### ISSUE TITLE
环境安装问题

### ISSUE THREAD

**Issue by Mohammed0821** [AFanSKyQs/FanSky_Qs#29]
ENOTEMPTY  ENOTEMPTY: directory not empty, unlink 'C:\Users\xxxxxxx\Desktop\yunzai\Miao-Yunzai\plugins\Guoba-Plugin\node_modules\body-parser'
 这个是在插件目录下的报错
 和锅巴冲突了好像是？

**Comment by AFanSKyQs** [comment]
emmmm有没有一种可能，不是我插件产生的报错.....
可能：pnpm install检测了整个云崽环境，顺便给其他插件需要的也安装了

**Comment by AFanSKyQs** [comment]
我的里面就俩依赖，axios和markdown-it，不可能有问题的，考虑重装依赖

**Comment by AFanSKyQs** [comment]
云崽根目录
cd plugins/FanSky_Qs

pnpm install 

就是进入我的插件文件夹，然后根据文件夹内的package.json内的依赖来安装该插件的依赖，相当于局部依赖，安装完成后会在FanSky_Qs文件夹内生成一个node_modules，插件运行也就是读取的这里面的依赖，不会影响到其他插件的

**Comment by AFanSKyQs** [comment]
说了已经cd进入我的插件文件夹内了，是安装的我插件的局部的单独的依赖，不会影响到其他插件的依赖，也不会影响到全局依赖，所以不存在冲突一说........,单纯地你依赖没装好...

**Comment by AFanSKyQs** [comment]
emmm，方便加我QQ，用向日葵或者todesk看看吗，可能是个别环境问题，不然其他人应该早有反映

**Comment by AFanSKyQs** [comment]
没有接收到3141865879，或者考虑加一下主页的群聊
