### ISSUE TITLE
还是无法更新米游社的数据。

### ISSUE THREAD

**Issue by light0220** [AFanSKyQs/FanSky_Qs#32]
并非cookie或验证码的问题，因为我首先使用了本插件的 #成就排行 命令，得到的是784个成就，这个应该是我的本地数据，
![image](https://user-images.githubusercontent.com/95893687/232950960-4b58fd8e-8157-4572-9ecd-289382f09ce3.png)

然后我立即使用喵喵插件的 #成就 命令，可见成就数是824个，这个数据与我米游社的数据是能够对应上的，证明喵喵插件能够成功查询米游社成就数据并未遇到验证码，那么本插件行于喵喵插件查询理应不会遇到验证码。而且我多次尝试，结果都是相同。
![image](https://user-images.githubusercontent.com/95893687/232951069-43b7d15d-2e0c-4095-881d-c89c8ea6ab22.png)
![D E){29K{7HC~O$J~03J9R7](https://user-images.githubusercontent.com/95893687/232954172-ca9e7522-2ad4-4efc-b18e-5129144f50dc.jpg)

而群友没有本地记录的情况下使用 #成就排行 命令则会是如下提示，并且每个没有本地数据的群友都是这样子的。进一步证明无法更新米游社数据。
![image](https://user-images.githubusercontent.com/95893687/232952687-28749ce8-9dda-47cb-ac19-9a36308c8c84.png)

终端运行截图如下：
这是有本地数据的截图
![image](https://user-images.githubusercontent.com/95893687/232953412-cb417a92-0605-4ff9-8175-56af83bfb12a.png)
这是没有本地数据的群友的截图
![image](https://user-images.githubusercontent.com/95893687/232953845-224f01b9-4bac-468c-9278-48f5363bd670.png)

**Comment by light0220** [comment]
刚更新了插件，已经可以更新米游社的数据了，但是还存在以下问题：

第一，明明可以访问米游社数据了，可是当之前没有本地数据的用户使用 #成就排行 命令后还是会提示以下消息。
![image](https://user-images.githubusercontent.com/95893687/232962870-d27a3afa-7d0a-4ab5-937e-264e793332dd.png)

第二，使用 #成就排行榜 命令后，之前没有本地数据用户信息无法显示排名、得分和称号等数据，如下图中，第二名是我（已经有本地数据），第一、三名的群友是第一次在本群中使用 #成就排行 命令（没有本地数据）。
![image](https://user-images.githubusercontent.com/95893687/232963712-a2a4f636-f598-42e1-9651-9643511d07fc.png)

**Comment by AFanSKyQs** [comment]
提示不是说了吗，接口没有信息，【尝试读取uid的本地数据】，本地数据哪来的全服排行，成就做的是成就数量的排行，所以得分和称号也没处理了，这些本应该都是接口返回的

**Comment by AFanSKyQs** [comment]
有没有验证码不是某一个账号能够决定和验证的，而且很多情况下即使绑了ck也会查询失败那个提示《米游社遇到验证码，请稍后重试》，还有的查询失败并没有做提示处理，而是直接拿历史数据展示
