### ISSUE TITLE
这uid和我绑定的uid最后一位不一样

### ISSUE THREAD

**Issue by zhangwenhao000** [AFanSKyQs/FanSky_Qs#34]
![0E3D830DDBC15A8EE0F4B1537A0A69E3](https://user-images.githubusercontent.com/112795404/233108203-1b58a01f-1fa0-4c25-bb89-e5ea3d5dee2e.jpg)

**Comment by AFanSKyQs** [comment]
重新使用#绑定 命令绑定你的uid，且更新到最新版本
