### ISSUE TITLE
TypeError: raw.buff is not iterable 报错

### ISSUE THREAD

**Issue by OriginSXC** [AFanSKyQs/FanSky_Qs#35]
![J33_NV{ `PYYOS)$}BESB1](https://user-images.githubusercontent.com/127317551/233238432-f72eef36-a686-4a37-ae30-4796244a1e88.png)
请问这个报错是因为不支持旅行者的数据吗？

**Comment by AFanSKyQs** [comment]
对的，不支持任何一位主角的伤害计算，因为主角元素有多种，目前没有计算功能
