### ISSUE TITLE
功能问题

### ISSUE THREAD

**Issue by PeelSign** [AFanSKyQs/FanSky_Qs#36]
请问，我只想使用队伍伤害功能，怎么能把其余功能关闭。
或者有单独的队伍伤害插件吗

**Comment by AFanSKyQs** [comment]
不触发=关闭，插件本身没有自动触发的东西，如果有触发说明有人用，如果是误触，可以具体描述一下误触功能，尝试增加逻辑，插件本身后面也会趋于模块化

**Comment by PeelSign** [comment]
功能太繁琐了，希望后面能精简一些。比如Chat的加载提示，希望后续能加上开关。

**Comment by AFanSKyQs** [comment]
等下次模块化调整就把功能模块开关都整上，启动配置提示也确实没什么用了。都会更新的ε(*･ω･)_/ﾟ:･☆

**Comment by PeelSign** [comment]
貌似我要调试Bot的时候，你的Chat插件会进入无限Debug模式。这导致我要先移除你的插件才能调试
