### ISSUE TITLE
今天更新完不能计算四人以下的队伍伤害了

### ISSUE THREAD

**Issue by akmioto** [AFanSKyQs/FanSky_Qs#37]
现在组队伤害强制四人才能计算，希望可以修复下

**Comment by AFanSKyQs** [comment]
已解除人数限制，但最低2人 >>> 284c1f4f75ec1f71ed64ce57281d1b20257b7bbe

**Comment by akmioto** [comment]
> 已解除人数限制，但最低2人 >>> [284c1f4](https://github.com/AFanSKyQs/FanSky_Qs/commit/284c1f4f75ec1f71ed64ce57281d1b20257b7bbe)

插件可以实现1人的伤害计算，需要把角色名字重复输入两次就可以了，能否解除限制？
