### ISSUE TITLE
【功能需求】Bilibili自定推送和管理功能

### ISSUE THREAD

**Issue by Oishiimono** [AFanSKyQs/FanSky_Qs#38]
目前已有的B站/米游社插件推送感觉都不是很完善，具体问题包括：
（1）闲心插件不适配Miao-Yunzai已经没法用了；但可以让管理员在config文档中自己添加需要推送的Q群号以及B站账号，不限于原神官方，还可以自己去添加比如崩铁，甚至是群友B站的直播推送（只需要B站UID，区分资讯推送和直播推送两大类）
（2）榴莲插件里的js插件太多（不太需要这么多），而且只能推送B站原神，貌似不能自选其他账号
（3）云崽/喵崽自带的只能推送米游社中的原神官方公告和资讯，且不支持后台手动集中管理；这种比较麻烦的在于，如果是机器人租借出去的群，管理员不在群里就不能添加推送功能

梳理一下功能需求大致就是：B站截图推送；可支持任意B站UID账号的推送；可支持直播开播的推送；支持在后台某个config文件能手动修改推送的Q群号信息和推送的B站账号信息

如果FanSky大佬有兴趣搞个这种功能，个人感觉闲心那个基础比较好可以用那个来起步，自定义空间相对较大，可惜他们没太更新来适配云崽。（愿意发电，欢迎大佬提供二维码）

**Comment by akmioto** [comment]
闲心插件喵云崽目前应该是可用的，我这没问题，榴莲插件的推送用的白纸插件那个，你可以单独装白纸插件（这个可以后台添加，比较麻烦，具体是修改Miao-Yunzai\data\PushNews\PushBilibiliDynamic，修改完需要重启Redis，否则不生效），本人目前闲心和白纸搭配使用，闲心推送直播，白纸推送其他，当然FanSky大佬能搞一个功能更完善的我双手赞成，目前这两个插件各有各的问题

**Comment by Oishiimono** [comment]
> 闲心插件喵云崽目前应该是可用的，我这没问题，榴莲插件的推送用的白纸插件那个，你可以单独装白纸插件（这个可以后台添加，比较麻烦，具体是修改Miao-Yunzai\data\PushNews\PushBilibiliDynamic，修改完需要重启Redis，否则不生效），本人目前闲心和白纸搭配使用，闲心推送直播，白纸推送其他，当然FanSky大佬能搞一个功能更完善的我双手赞成，目前这两个插件各有各的问题

确实是期待大佬搞一个功能更完善的

**Comment by lintonxue00** [comment]
白纸的就挺好的呀，我就是用它的，挺不错的

**Comment by lintonxue00** [comment]
我觉得可以考虑做p站推送，大佬可以参考[nonebot-plugin-pixivbot](https://github.com/ssttkkl/nonebot-plugin-pixivbot)这个项目，不过py插件不适配的，我只能再开个服务器用nb cli部署，刷新令牌获取有一点难度但不难

**Comment by lintonxue00** [comment]
![image](https://user-images.githubusercontent.com/115356968/234571315-c24c9646-ee86-4f6a-8328-690bf41e26dc.png)
![image](https://user-images.githubusercontent.com/115356968/234571384-72fcc4d6-0f50-4698-92e0-866ab5773a0c.png)
![image](https://user-images.githubusercontent.com/115356968/234571585-e211faa6-7f09-42ad-b7ad-6949664036ca.png)

**Comment by lintonxue00** [comment]
微博订阅大佬可以考虑下，因为云崽还没有人做呢

**Comment by lintonxue00** [comment]
nb plugin install nonebot-bison可以参考下这个插件

**Comment by Rrrrrrray** [comment]
建议装白纸，把随机表情那几个rule注释掉就可以了
![QQ图片20230502145636](https://user-images.githubusercontent.com/28804884/235600117-5ec15cda-7459-4602-8d70-e582f2f6447d.jpg)
另外云崽自带推送是有配置文件管理的只是没有指令入口
