### ISSUE TITLE
点赞/赞我等功能是否可以设置开关

### ISSUE THREAD

**Issue by Oishiimono** [AFanSKyQs/FanSky_Qs#4]
大佬好，想问问看比如点赞/赞我这类比较流行的功能，在千羽、椰羊之类的插件也有了，不知道是否可以设置一个开关（或者优先级调整）指令，这样可以灵活在各插件间切换或开关相应的同种功能呢？

**Comment by AFanSKyQs** [comment]
好的，马上加个开关~
