### ISSUE TITLE
今天更新后出现teyvatTooksIndex载入错误

### ISSUE THREAD

**Issue by wzq10314** [AFanSKyQs/FanSky_Qs#40]
![QQ图片20230421173052](https://user-images.githubusercontent.com/21983217/233601392-b756fae0-24aa-4169-aa6c-5bdf65d262a2.png)

**Comment by akmioto** [comment]
等dalao修复吧 可以先退回旧版 在FanSky_Qs文件夹运行命令git reset --hard 284c1f4

**Comment by wzq10314** [comment]
> 等dalao修复吧可以先退回旧版在FanSky_Qs文件夹运行命令git reset --hard [284c1f4](https://github.com/AFanSKyQs/FanSky_Qs/commit/284c1f4f75ec1f71ed64ce57281d1b20257b7bbe)
好的！
