### ISSUE TITLE
原版云崽能用吗？

### ISSUE THREAD

**Issue by Daroach0** [AFanSKyQs/FanSky_Qs#41]
还是只能在喵云崽上面用？求大佬指示

**Comment by AFanSKyQs** [comment]
原版云崽停更，目前主要有两个版本：
1、miao源的云崽，通过指令换一下仓库即可使老版云崽更新上去
2、miao崽，在云崽的基础上做了一些修改，是目前主要维护的。只需要将原版数据资源配置文件迁移一下即可用
如果还是云崽/喵崽范畴推荐更新一下。
如果是其他平台，那可能需要平台做一些适配
