### ISSUE TITLE
[队伍伤害]角色展示技能图标错乱,不显示图标,模块之间无间隔

### ISSUE THREAD

**Issue by mmmooyuFei** [AFanSKyQs/FanSky_Qs#42]
![QQ截图20230422162742](https://user-images.githubusercontent.com/29856831/233772847-dd601a73-0e3e-4539-844c-895cdbd099db.jpg)
![C % @6DIROV)YC7% UBA$PX](https://user-images.githubusercontent.com/29856831/233773042-355189fc-b394-4f3e-aae7-0f5ff39c10a9.png)

以下正确的技能图标
![image](https://user-images.githubusercontent.com/29856831/233773280-e6b18fc2-a9dc-4d74-ad22-5ace3dab0117.png)

**Comment by AFanSKyQs** [comment]
嗯嗯，后续会调整的
