### ISSUE TITLE
Function increment-Add Cxk emo

### ISSUE THREAD

**Issue by xiaozuo7** [AFanSKyQs/FanSky_Qs#5]
1.既然有丁真giegie
2.应该也能做只因哥哥吧

我是做后端的，不怎么会js，不过要是增加同样的模块不复杂，也可以跟着搞。
但是需要知道具体代码实现在哪里

**Comment by AFanSKyQs** [comment]
FanSky_Qs/apps/SmallFunctions/YiyanDinZhen.js，逻辑比较简单，如果有图库或者api可以顺便弄喵~

**Comment by Oishiimono** [comment]
> FanSky_Qs/apps/SmallFunctions/YiyanDinZhen.js，逻辑比较简单，如果有图库或者api可以顺便弄喵~

期待你们的组队伤害！！！终于有了！！！

**Comment by AFanSKyQs** [comment]
> > FanSky_Qs/apps/SmallFunctions/YiyanDinZhen.js，逻辑比较简单，如果有图库或者api可以顺便弄喵~
> 
> 期待你们的组队伤害！！！终于有了！！！

![image](https://user-images.githubusercontent.com/59954030/226341896-6341810b-1941-4918-95d2-2463bb47e012.png)
