### ISSUE TITLE
命令失效

### ISSUE THREAD

**Issue by xiaobingnt** [AFanSKyQs/FanSky_Qs#52]
一眼丁真指令没反应了

**Comment by AFanSKyQs** [comment]
插件本身的指令是没有问题的，可能原因
1：被其他插件抢了，这种功能可能有很多插件有，你可能装了类似的且报错了没出得来图
2：#fan设置娱乐系统关闭 了，一眼丁真是娱乐系统内的功能，关闭将不响应
