### ISSUE TITLE
#队伍伤害  夜兰 万叶 班尼特 香菱 手法错误

### ISSUE THREAD

**Issue by snowtafir** [AFanSKyQs/FanSky_Qs#58]
![Screenshot_2023-06-14-16-36-19-27_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/AFanSKyQs/FanSky_Qs/assets/62873988/fa4bd5fc-5cf1-49c0-8fbc-f6ed4a53af74)

**Comment by AFanSKyQs** [comment]
这个是微信小助手的默认手法噢，插件暂不支持自定义手法~
