### ISSUE TITLE
指令-【发病】增加别名【发电】

### ISSUE THREAD

**Issue by xiaozuo7** [AFanSKyQs/FanSky_Qs#6]
发病的网络流行词语叫发电，应当尽量避免发病这种过于直白的表达

**Comment by AFanSKyQs** [comment]
本来就有这个别名噢~

**Comment by AFanSKyQs** [comment]
![image](https://user-images.githubusercontent.com/59954030/226341809-42e4bbda-43cc-4ab5-8532-de620a51ca05.png)
