### ISSUE TITLE
队伍伤害报错TypeError: Cannot read properties of undefined (reading 'e')

### ISSUE THREAD

**Issue by Oishiimono** [AFanSKyQs/FanSky_Qs#68]
![image](https://github.com/AFanSKyQs/FanSky_Qs/assets/34758515/f44f18fb-42a0-4e9e-9aa8-dd312f76a378)

“this.e”？

**Comment by Coldbaiwu** [comment]
这个要咋解决啊

**Comment by Oishiimono** [comment]
应该是间歇性的问题，已自愈；也有可能是其他插件解决了它
