### ISSUE TITLE
打卡图片发不出

### ISSUE THREAD

**Issue by sizxiwu** [AFanSKyQs/FanSky_Qs#7]
[YzBot][20:21:58.180][MARK] [liulian-plugin][dispatch] 打卡 处理完成 0ms
[YzBot][20:21:58.186][WARN] 图片1失败, reason: getaddrinfo ENOTFOUND api.iyk0.com
[YzBot][20:21:58.808][INFO] succeed to send: [Group(128538652)] @-_- 打卡成功!这是给你的奖励![图片]
ps:点赞要加好友私聊:打卡

**Comment by AFanSKyQs** [comment]
“ [liulian-plugin] “这个不是我的插件噢喵~，下面这个才是噢，应该是指令被那个插件抢掉了~
![image](https://user-images.githubusercontent.com/59954030/226338560-ac55c40f-72c4-4336-abbc-b03deca4f73f.png)
