### ISSUE TITLE
NTQQ登录的喵崽运行队伍伤害报错

### ISSUE THREAD

**Issue by touchscale** [AFanSKyQs/FanSky_Qs#71]
![Image_1699592112938.png](https://github.com/AFanSKyQs/FanSky_Qs/assets/107158734/d362a0b3-a2b8-4bb1-9ab1-2497c6505529)

**Comment by touchscale** [comment]
似乎带上水神就会触发这段报错

**Comment by touchscale** [comment]
> 似乎带上水神就会触发这段报错
 
不带就可以正常返回

**Comment by touchscale** [comment]
![Screenshot_2023-11-10-12-58-37-036_com.tencent.mobileqq-edit.jpg](https://github.com/AFanSKyQs/FanSky_Qs/assets/107158734/b9022cf2-6570-4dcc-bf54-49f767b10124)

**Comment by Oishiimono** [comment]
现在水神能正常出了，就是那维的武器和猎人套的图标还是会偏移

**Comment by touchscale** [comment]
现在可以正常发出了，但是buff少了一个水神大招的气氛值增伤

**Comment by touchscale** [comment]
![Image_1701127657170.jpg](https://github.com/AFanSKyQs/FanSky_Qs/assets/107158734/8af974a0-c1f6-41c6-bce3-a04b91dcb460)
