### ISSUE TITLE
功能需求：Yunzai版memes/petpet

### ISSUE THREAD

**Issue by Oishiimono** [AFanSKyQs/FanSky_Qs#9]
看到“需要什么功能可以提出来，尽量实现喵~”所以想来问下看nonebot的memes/petpet这种插件功能能不能在Yunzai（非python）环境上实现啊

**Comment by AFanSKyQs** [comment]
可以实现，但是可能需要一些时间来重写，比如下面是通过js来调用canvas生成的"喜报",时间有点紧
![image](https://user-images.githubusercontent.com/59954030/226618621-52ca2951-3ec7-4389-b431-ace46d1f9a81.png)
![image](https://user-images.githubusercontent.com/59954030/226618865-8a5232a5-6582-402a-9c6e-231b6f2a742b.png)

**Comment by RemYui** [comment]
> 看到“需要什么功能可以提出来，尽量实现喵~”所以想来问下看nonebot的memes/petpet这种插件功能能不能在Yunzai（非python）环境上实现啊

py-plugin不是已经有了吗？可以远程连接，不用安装python

**Comment by RemYui** [comment]
> > > 看到“需要什么功能可以提出来，尽量实现喵~”所以想来问下看nonebot的memes/petpet这种插件功能能不能在Yunzai（非python）环境上实现啊
> > 
> > 
> > py-plugin不是已经有了吗？可以远程连接，不用安装python
> 
> ![image](https://user-images.githubusercontent.com/34758515/226848529-470216a5-8131-4eeb-a0bb-a53f9627303b.png) py-plugin要装python的呀超麻烦

![image](https://user-images.githubusercontent.com/72900249/226928493-89d5ef84-8259-4d06-8f83-cfd54db67e94.png)
使用远程就行了啊，克隆插件之后修改config.yaml文件就行，不用装python的

**Comment by Oishiimono** [comment]
> > > > 看到“需要什么功能可以提出来，尽量实现喵~”所以想来问下看nonebot的memes/petpet这种插件功能能不能在Yunzai（非python）环境上实现啊
> > > 
> > > 
> > > py-plugin不是已经有了吗？可以远程连接，不用安装python
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34758515/226848529-470216a5-8131-4eeb-a0bb-a53f9627303b.png) py-plugin要装python的呀超麻烦
> 
> ![image](https://user-images.githubusercontent.com/72900249/226928493-89d5ef84-8259-4d06-8f83-cfd54db67e94.png) 使用远程就行了啊，克隆插件之后修改config.yaml文件就行，不用装python的

是在不好意思，我连第一步poetry都不会搞……

**Comment by Oishiimono** [comment]
> > > > > > 看到“需要什么功能可以提出来，尽量实现喵~”所以想来问下看nonebot的memes/petpet这种插件功能能不能在Yunzai（非python）环境上实现啊
> > > > > 
> > > > > 
> > > > > py-plugin不是已经有了吗？可以远程连接，不用安装python
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/34758515/226848529-470216a5-8131-4eeb-a0bb-a53f9627303b.png) py-plugin要装python的呀超麻烦
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/72900249/226928493-89d5ef84-8259-4d06-8f83-cfd54db67e94.png) 使用远程就行了啊，克隆插件之后修改config.yaml文件就行，不用装python的
> > 
> > 
> > 是在不好意思，我连第一步poetry都不会搞……
> 
> 直接看第5步就行啦，远程那边python和依赖都装好了，克隆插件修改配置文件就行

多谢大佬，这下部署好了

**Comment by Oishiimono** [comment]
py-plugin本地版：memes无法响应指令
py-plugin远程版：服务器不稳定偶尔挂掉

结论：如果大佬们有兴趣，真的可以考虑开发一个基于云崽的这个插件呢
